### ISSUE TITLE
CLI help text

### ISSUE THREAD

**Issue by mallika2608** [Paradoxika/Skeptik#104]
Just a minor bug. Running the command `skeptik --help` displays the usage help, which is still showing "compress" in the usage text. Whereas, I think that has been updated to "skeptik". 

(Example [here](http://imgur.com/uxZahFR)) 

Should I change this and submit a pull request or will one of you folks do it?

**Comment by Ceilican** [comment]
Indeed.
It would be great if you could fix it and send a pull request.

**Comment by mallika2608** [comment]
Done, sent a pull request.

**Comment by Ceilican** [comment]
Thank you, @mallika2608 !
