### ISSUE TITLE
TopDown RecycleUnits

### ISSUE THREAD

**Issue by Ceilican** [Paradoxika/Skeptik#80]
Like RecycleUnits, but with a top-down traversal. Easy to implement, but not high-priority, because this won't compress much, if it compresses at all.

**Comment by mallika2608** [comment]
Where can I look at the current implementation of RecycleUnits? Is there one?

**Comment by Ceilican** [comment]
Here it is: https://github.com/Paradoxika/Skeptik/blob/develop/src/main/scala/at/logic/skeptik/algorithm/compressor/RecycleUnits.scala
